version: '3.7'
services:
  app:
    build: .
    command: bin/rails server --binding=0.0.0.0
    environment:
      - LANG=C.UTF-8
      - ONIWA_DATABASE_HOST=db
      - PAGER=more
      - RAILS_ENV=development
    ports:
      - 11024:3000
    stdin_open: true
    tty: true
    volumes:
      - .:/opt/oniwa
  db:
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      - LANG=C.UTF-8
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    image: mysql:8.0.17
    volumes:
      - /var/lib/mysql
